# ClearItem - 服务器清理与垃圾箱系统
# 作者: Luo_ma, KlNon
# 版本: 3.3.5.1


# 部分指令提示前缀
Prefix: "§8[§bClearItem§8] "

# ======================== #
#      公共垃圾箱系统      #
# ======================== #
# 提供一个公共垃圾箱供玩家存放和处理不需要的物品
PublicDustbin:
  # 是否启用公共垃圾箱功能
  Enable: true
  # 垃圾箱名称和提示
  Name: "&c&l服务器垃圾箱"
  Action: "&b&l>> &f打开了"
  # 垃圾箱容量(必须是9的倍数,建议54-270之间)
  Size: 135
  
  # 翻页按钮设置
  PrePageName: "&9&l« &f上一页"
  PrePageDes: "&7点击返回上一页"
  NextPageName: "&f下一页 &9&l»"
  NextPageDes: "&7点击前往下一页"
  
  # 自动清理设置
  # 当系统清理掉落物N次后会自动清空垃圾箱
  ClearInterval: 4
  
  # 物品白名单(这些物品不会被放入垃圾箱)
  WhiteListName:
    - "§q§s"  # 防止QS插件的悬浮物品被放入
  
  # 消息提示设置
  Message:
    # 物品进入垃圾箱提示
    Reminder: '&8[&b垃圾箱&8] &f新增了 &e%amount% &f个物品'
    # 打开按钮
    Button: '&8[&e点击打开垃圾箱&8]'
    ButtonInfo: '&7点击打开服务器垃圾箱'
    # 清理提示
    Clear: "&8[&b垃圾箱&8] &f已自动清空垃圾箱"

# ======================== #
#      私人垃圾箱系统      #
# ======================== #
# 为每个玩家提供一个私人垃圾箱,关闭时物品会自动转移到公共垃圾箱
PrivateDustbin:
  Enable: true
  Name: "&3&l个人垃圾箱 &8(&7物品会自动转移至公共垃圾箱&8)"
  Action: "&b&l>> &f打开了"
  Size: 54
  
  # 物品保护(这些物品不会被转移)
  WhiteListName:
    - "§q§s"  # 防QS物品
  WhiteListLore:
    - "绑定"  # 绑定物品
    - "禁止丢弃"
  
  Message:
    Clear: "&8[&b垃圾箱&8] &f已清理 &a%clear% &f个物品&7, &f保留 &e%preserve% &f个物品"

# ======================== #
#      物品防丢弃系统      #
# ======================== #
# 防止玩家误丢重要物品的保护机制
Drop:
  Enable: true
  # 是否启用重新锁定
  EnableTimer: false
  # 解锁后自动重新锁定时间(秒)
  Time: 300
  
  Message:
    Open: "&8[&a✓&8] &f已开启物品保护"
    Close: "&8[&c✗&8] &7已临时关闭物品保护 &8(&f%time%秒后恢复&8)"
    CloseNoTimer: "&8[&c✗&8] &7已临时关闭物品保护"
    DiscardInOpen: "&8[&e!&8] &f物品保护已开启&7, &f输入 &e/citem drop &f临时解除"


# ======================== #
#      共享物品空间      #
# ======================== #
ShareInv:
  Enable: true
  # 箱子名称
  Name: "&3&l共享空间"
  # 箱大小
  Size: 54
  # 打开动作
  Action: "&b打开了"
  # 上一页页码的文字
  PrePageName: "&9上一页"
  # 上一页页码的描述
  PrePageDes: "&9点此上一页"
  # 下一页页码的文字
  NextPageName: "&9下一页"
  # 下一页页码的描述
  NextPageDes: "&9点此下一页"
  #  清理时间(默认10分钟，单位秒)
  ClearTime: 600
  # 清理前的消息
  Message:
    ClearMessagePre:
      "&c[警告] &6共享空间将会在 &e%time%秒 &6后清理，请及时取走重要物品!"
    ClearMessageStart:
      "&c[警告] &6共享空间正在清理. 注意安全!"
    ClearMessageEnd:
      "&c[警告] &6共享空间清理完毕!"
    ButtonMessage:
      "点此打开共享空间"
    ButtonInfo:
      "这是一个共享空间"


# ======================== #
#      掉落物清理系统      #
# ======================== #
# 定时清理世界掉落物,防止卡服
ClearItem:
  # 清理间隔(秒)
  Time: 60
  # 区块物品堆积阈值(当16*32*16范围内的掉落物超过此数量时触发清理)
  ChunkMaxItems: 500
  
  # 物品白名单(这些物品不会被清理)
  WhiteList:
    - "EXTRABOTANY_GAIATABLET"
    - "BOTANIA_MANATABLET"
    - "BEACON"
    - "BOTANIA_MANARINGGREATER"
    - "BOTANIA_TERRAPICK"
  
  # 实体清理设置
  ItemFrame: false    # 物品展示框
  Boat: false        # 船只
  ExpBall: true      # 经验球
  FallingBlock: false # 掉落方块
  Painting: false    # 画
  Minecart: false    # 矿车
  Arrow: true        # 箭矢
  Snowball: true     # 雪球
  
  Message:
    # 清理预警
    ClearPre: "&8[&c!&8] &f将在 &e%time%秒 &f后清理掉落物"
    # 开始清理
    ClearStart: "&8[&c!&8] &f正在清理掉落物&7, &f请注意保管重要物品"
    # 清理完成统计
    Clear: "&8[&b系统&8] &f本次共清理了 &e%count% &f个掉落物"
    # 单个世界统计
    ClearWorld: "&8[&b系统&8] &f在 &e%world% &f清理了 &e%count% &f个掉落物"
    # 区块堆积清理
    ClearChunkMaxItems: "&8[&c!&8] &f世界: &b%world% &f坐标: &e%X% %Y% %Z% &c区域物品堆积&7, &f已自动清理"

# ======================== #
#        显示设置         #
# ======================== #
CleaningTips:
  # 是否启用全局统计
  # true: 只显示总清理数量
  # false: 分世界显示清理数量
  Enable: true
  
  # 世界显示名称
  WorldAlias:
    world: "主世界"
    world_nether: "地狱"
    world_the_end: "末地"
    spawn: "出生点"
    survival: "生存世界"
    creative: "创造世界"
